services:

  www:
    image: httpd:latest
    depends_on:
      - server
    ports:
      - "80:80"
    volumes:
      - ./src/client:/usr/local/apache2/htdocs
      - ./data:/var/www/data
    networks:
      - network

  server:
    build: ./src/server
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src/server:/app
    networks:
      - network

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: dashboard
      MYSQL_USER: webuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    networks:
      - network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - network

networks:
  network:
    driver: bridge
