services:

  www:
    image: httpd:latest
    depends_on:
      - server
    volumes:
      - ./src/client:/usr/local/apache2/htdocs
      - ./data:/var/www/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.olvi-dashboard.rule=Host(`olvi-dashboard.services.dsi.wisc.edu`)"
      - "traefik.http.routers.olvi-dashboard.entrypoints=websecure"
      - "traefik.http.routers.olvi-dashboard.tls=true"
      - "traefik.http.routers.olvi-dashboard.tls.certresolver=myresolver"
    networks:
      - traefik_network

  server:
    build: ./src/server
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src/server:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.olvi-dashboard-api.rule=Host(`olvi-dashboard-api.services.dsi.wisc.edu`)"
      - "traefik.http.routers.olvi-dashboard-api.entrypoints=websecure"
      - "traefik.http.routers.olvi-dashboard-api.tls=true"
      - "traefik.http.routers.olvi-dashboard-api.tls.certresolver=myresolver"
    networks:
      - traefik_network

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: dashboard
      MYSQL_USER: webuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - traefik_network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
